# Data loading and cleaning
```{r}
library(tidyverse)
antibiotics_list <- read_csv("hospital-antibiotics.csv")
```

## Generate sample of unique antibiotic administrations
```{r}
antibiotics <- read_csv("mimic-demo/PRESCRIPTIONS.csv") |>
    filter(drug %in% antibiotics_list$Antibiotic) |>
    mutate(
        drug = as.factor(drug),
        antibiotic_key = paste(subject_id, hadm_id, icustay_id, row_id, drug, sep = "_")
    ) |>
    rename(
        ab_startdate = startdate,
        ab_enddate = enddate,
    ) |>
    left_join(
        antibiotics_list,
        by = c("drug" = "Antibiotic")
    ) |>
    # select(
    #     # row_id,
    #     subject_id,
    #     hadm_id,
    #     icustay_id,
    #     antibiotic_key,
    #     drug,
    #     drug_class,
    #     ab_startdate,
    #     ab_enddate,
    #     dose_val_rx,
    #     dose_unit_rx) |>
    pivot_wider(
        id_cols = c(subject_id, hadm_id, icustay_id, antibiotic_key, ab_startdate, ab_enddate),
        names_from = drug_class,
        values_from = drug_class,
        names_prefix = "ab_class_is_"
    )
```

## Load *C. diff* diagnosis info
```{r}
cdiff_tests <- read_csv("mimic-demo/MICROBIOLOGYEVENTS.csv") |>
    filter(org_itemid == 80139) |> # code for C. difficile
    rename(
        cdiff_charttime = charttime,
    ) |>
    select(
        subject_id,
        hadm_id,
        cdiff_charttime,
        org_itemid
    )
cdiff_icd9 <- read_csv("mimic-demo/DIAGNOSES_ICD.csv") |>
    filter(icd9_code == "00845") |> # code for C. difficile
    rename(cdiff_icd9 = icd9_code) |>
    select(
        subject_id,
        hadm_id,
        cdiff_icd9
    )

diarrhea_icd9 <- read_csv("mimic-demo/DIAGNOSES_ICD.csv") |>
    filter(icd9_code == "78791") |> # code for C. difficile
    rename(diarrhea_icd9 = icd9_code) |>
    select(
        subject_id,
        hadm_id,
        diarrhea_icd9
    )
```

## Load patient demographics
```{r}
admissions <- read_csv("mimic-demo/ADMISSIONS.csv")
patients <- read_csv("mimic-demo/PATIENTS.csv")

demographics <- admissions |>
    left_join(patients, by = c("subject_id")) |>
    mutate(
        is_female = ifelse(
            gender == "F",
            yes = TRUE,
            no = FALSE
        )
    ) |>
    select(
        subject_id,
        hadm_id,
        is_female,
        dob,
        admittime,
        dischtime,
        admission_type,
        insurance,
        diagnosis,
    )
```

## Load ICU status
```{r}
icustays <- read_csv("mimic-demo/ICUSTAYS.csv") |>
    rename(icu_intime = intime, icu_outtime = outtime) |>
    select(
        subject_id,
        hadm_id,
        icustay_id,
        first_careunit,
        last_careunit,
        icu_intime,
        icu_outtime
    )
```

## Load lab values
```{r}
labvalues <- read_csv("mimic-demo/LABEVENTS.csv")
```
### Liver
```{r}
# item_id dictionary
liver_lab_itemids <- list(
    bilirubin_total = 50885,
    alkaline_phosphatase = 50863,
    alanine_transaminase = 50861,
    aspartate_aminotransferase = 50878,
    gamma_glutamyltransferase = 50927
)
# Set QC thresholds for lab values
lab_qc_thresholds <- c(
    "bilirubin_total" = 20,
    "alkaline_phosphatase" = 600,
    "alanine_transaminase" = 100,
    "aspartate_aminotransferase" = 100,
    "Gamma_glutamyltransferase" = 170
)

liver_labs <- labvalues |>
    filter(itemid %in% liver_lab_itemids) |>
    # Map itemid to iterpretable name using dictionary
    mutate(
        test_name = as.factor(case_when(
            itemid == liver_lab_itemids$bilirubin_total ~ names(liver_lab_itemids)[1],
            itemid == liver_lab_itemids$alkaline_phosphatase ~ names(liver_lab_itemids)[2],
            itemid == liver_lab_itemids$alanine_transaminase ~ names(liver_lab_itemids)[3],
            itemid == liver_lab_itemids$aspartate_aminotransferase ~ names(liver_lab_itemids)[4],
            itemid == liver_lab_itemids$gamma_glutamyltransferase ~ names(liver_lab_itemids)[5]
        ))
    ) |>
    # filter to lab-specific QC thresholds
    filter(valuenum < lab_qc_thresholds[test_name]) |>
    right_join(
        antibiotics,
        by = c("subject_id", "hadm_id"),
        relationship = "many-to-many" # each Ab will be associated with multiple labs, and each lab will be associated with multiple Abs, since eac admission (the key), may contain multiple Abs
    ) |>
    rename(lab_charttime = charttime) |>
    # filter to labs *prior* to admin time
    filter(lab_charttime < ab_startdate) |>
    # Summarize each lab value, grouped by administration instance
    group_by(subject_id, hadm_id, antibiotic_key, test_name) %>%
    summarize(
        mean = mean(valuenum, na.rm = TRUE),
        median = median(valuenum, na.rm = TRUE),
        max = max(valuenum, na.rm = TRUE),
        min = min(valuenum, na.rm = TRUE),
        # q10 = quantile(valuenum, 0.1, na.rm = TRUE),
        # q90 = quantile(valuenum, 0.9, na.rm = TRUE),
        range = max(valuenum, na.rm = TRUE) - min(valuenum, na.rm = TRUE),
        sd = replace_na(sd(valuenum, na.rm = TRUE), 0),
        iqr = IQR(valuenum, na.rm = TRUE),
        first = first(valuenum, na_rm = TRUE),
        last = last(valuenum, na_rm = TRUE),
        count = length(valuenum),
        .groups = "drop"
    ) %>%
    # WARNING: NAs appear for patients with zero instances of a given lab; these are only implicit in the unpivoted data, since test_name will just skip that lab for that patien
    pivot_wider(
        id_cols = c(subject_id, hadm_id, antibiotic_key),
        names_from = test_name,
        values_from = !(c(subject_id, hadm_id, antibiotic_key, test_name)),
        names_sep = "_"
    )
# View(liver_labs)
# write_csv(liver_labs, "liver_labs.csv")
```
### Renal
### Blood counts

## Join everything together and compute new columns
```{r}
training_data <- antibiotics |>
    left_join(
        cdiff_tests,
        by = c("subject_id", "hadm_id")
    ) |>
    left_join(
        cdiff_icd9,
        by = c("subject_id", "hadm_id")
    ) |>
    left_join(
        diarrhea_icd9,
        by = c("subject_id", "hadm_id"),
    ) |>
    left_join(
        demographics,
        by = c("subject_id", "hadm_id"),
    ) |>
    left_join(
        icustays,
        by = c("subject_id", "hadm_id", "icustay_id"),
    ) |>
    left_join(
        liver_labs,
        by = c("subject_id", "hadm_id", "antibiotic_key"),
    ) |>
    mutate(
        # generate age column
        age_at_admin = ab_startdate - dob,
        # generate variable for time since admission at Ab admin, mark 0 if same day since datetimes for Abs are not available
        admin_time_since_admission = pmax(ab_startdate - admittime, 0),
        in_icu = ifelse(
            ab_startdate >= icu_intime & ab_startdate <= icu_outtime,
            TRUE,
            FALSE
        ),
        # GENERATE LABEL:
        cdiff_30d_flag = ifelse(
            # OPTION 1: C. diff positive culture after Ab start and less than 30 days after
            (cdiff_charttime >= ab_startdate & cdiff_charttime <= ab_startdate + ddays(30))
            # OPTION 2: C. diff ICD (00845) assigned at end of stay, as long as discharge was <30 days after Ab start
            | (cdiff_icd9 == "00845" & dischtime <= ab_startdate + ddays(30)),
            # Assign TRUE/FALSE accordingly
            yes = TRUE,
            no = FALSE
        ),
        # ifelse() returns NA for missing data (non-Cdiff patients will have missing ICDs), so fill missing with FALSE
        cdiff_30d_flag = replace_na(cdiff_30d_flag, FALSE)
    )  |>
    select(-icu_intime, -icu_outtime)
View(training_data)
```
```{r}
write_csv(training_data, "training_data.csv")
```